[WIP] More cli changes

diff --git a/.githooks/pre-commit/cli-docs-up-to-date b/.githooks/pre-commit/cli-docs-up-to-date
--- a/.githooks/pre-commit/cli-docs-up-to-date
+++ b/.githooks/pre-commit/cli-docs-up-to-date
@@ -1,5 +1,14 @@
 #!/bin/sh
 
+grep -A 10000 'choose_command()' cli.sh |
+    grep -oE '"[a-z-]+")' | grep -oE '[a-z-]+' |
+    while read -r CLI_OPTION; do
+        if ! sh cli.sh help | grep '^  ' | grep -q " $CLI_OPTION "; then
+            echo "! Help option is missing for \`git hooks $CLI_OPTION\`"
+            MISSING=1
+        fi
+    done
+
 for HELP_OPTION in $(sh cli.sh help | grep '^  ' | awk '{ print $1 }'); do
     if ! grep -q "## git hooks $HELP_OPTION" docs/command-line-tool.md; then
         echo "! Documentation is missing for \`git hooks $HELP_OPTION\`"
